# Configuration settings

SAVE_MASK_DIR = "/Users/huayinluo/Documents/code/zhenlab/MultiscaleSEM/masks"
USE_PARENT_DIR_FOR_MASKS = True
MASK_OPACITY = 0.5
PREFETCH_RADIUS = 3
CENTERLINE_POINTS = 100
MODEL_SIZE = "base"
PLAY_INTERVAL_MS = 100
BATCH_SIZE = 2

# batch prompt settings
KERNEL_SIZE = 5
KERNEL_ITERATIONS = 5
NUM_POSITIVE_PROMPTS = 8
NEGATIVE_KERNEL_SIZE = 5
NEGATIVE_KERNEL_ITERATIONS = 3
NUM_NEGATIVE_PROMPTS = 30